
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#ifndef __GCAL_ENUM_TYPES_H__
#define __GCAL_ENUM_TYPES_H__

#include <glib-object.h>

G_BEGIN_DECLS
/* Enumerations from "/home/secureboot/Downloads/gnome-calendar/src/gcal-enums.h" */
#define GCAL_TYPE_TIME_FORMAT	(gcal_time_format_get_type())
GType gcal_time_format_get_type	(void) G_GNUC_CONST;
#define GCAL_TYPE_WINDOW_VIEW	(gcal_window_view_get_type())
GType gcal_window_view_get_type	(void) G_GNUC_CONST;
#define GCAL_TYPE_WEEK_DAY	(gcal_week_day_get_type())
GType gcal_week_day_get_type	(void) G_GNUC_CONST;
G_END_DECLS

#endif /* __GCAL_ENUM_TYPES_H__ */

/* Generated data ends here */

