
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#include "gcal-enum-types.h"
/* enumerations from "/home/secureboot/Downloads/gnome-calendar/src/gcal-enums.h" */
#include "/home/secureboot/Downloads/gnome-calendar/src/gcal-enums.h"
GType
gcal_time_format_get_type (void)
{
	static GType the_type = 0;

	if (the_type == 0)
	{
		static const GEnumValue values[] = {
			{ GCAL_TIME_FORMAT_12H,
			  "GCAL_TIME_FORMAT_12H",
			  "12h" },
			{ GCAL_TIME_FORMAT_24H,
			  "GCAL_TIME_FORMAT_24H",
			  "24h" },
			{ 0, NULL, NULL }
		};
		the_type = g_enum_register_static (
				g_intern_static_string ("GcalTimeFormat"),
				values);
	}
	return the_type;
}
GType
gcal_window_view_get_type (void)
{
	static GType the_type = 0;

	if (the_type == 0)
	{
		static const GEnumValue values[] = {
			{ GCAL_WINDOW_VIEW_WEEK,
			  "GCAL_WINDOW_VIEW_WEEK",
			  "week" },
			{ GCAL_WINDOW_VIEW_MONTH,
			  "GCAL_WINDOW_VIEW_MONTH",
			  "month" },
			{ GCAL_WINDOW_VIEW_YEAR,
			  "GCAL_WINDOW_VIEW_YEAR",
			  "year" },
			{ 0, NULL, NULL }
		};
		the_type = g_enum_register_static (
				g_intern_static_string ("GcalWindowView"),
				values);
	}
	return the_type;
}
GType
gcal_week_day_get_type (void)
{
	static GType the_type = 0;

	if (the_type == 0)
	{
		static const GFlagsValue values[] = {
			{ GCAL_WEEK_DAY_INVALID,
			  "GCAL_WEEK_DAY_INVALID",
			  "invalid" },
			{ GCAL_WEEK_DAY_SUNDAY,
			  "GCAL_WEEK_DAY_SUNDAY",
			  "sunday" },
			{ GCAL_WEEK_DAY_MONDAY,
			  "GCAL_WEEK_DAY_MONDAY",
			  "monday" },
			{ GCAL_WEEK_DAY_TUESDAY,
			  "GCAL_WEEK_DAY_TUESDAY",
			  "tuesday" },
			{ GCAL_WEEK_DAY_WEDNESDAY,
			  "GCAL_WEEK_DAY_WEDNESDAY",
			  "wednesday" },
			{ GCAL_WEEK_DAY_THURSDAY,
			  "GCAL_WEEK_DAY_THURSDAY",
			  "thursday" },
			{ GCAL_WEEK_DAY_FRIDAY,
			  "GCAL_WEEK_DAY_FRIDAY",
			  "friday" },
			{ GCAL_WEEK_DAY_SATURDAY,
			  "GCAL_WEEK_DAY_SATURDAY",
			  "saturday" },
			{ 0, NULL, NULL }
		};
		the_type = g_flags_register_static (
				g_intern_static_string ("GcalWeekDay"),
				values);
	}
	return the_type;
}

/* Generated data ends here */

